# Generated by Django 4.1.7 on 2023-12-02 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0003_blog_makessdsr'),
        ('shared_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='b1log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blogger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogger.blog_makessdsr')),
            ],
        ),
    ]
