# Generated by Django 4.1.7 on 2023-12-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_app', '0002_b1log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='b1log',
        ),
    ]
