# Generated by Django 4.1.7 on 2023-12-02 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_app', '0004_like_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_blog',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='shared_app.blog'),
        ),
    ]
