# Generated by Django 4.1.7 on 2023-12-03 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0004_delete_blog_makessdsr'),
        ('shared_app', '0005_alter_like_blog_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shared_app.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogger.blog_maker')),
            ],
        ),
    ]
