# Generated by Django 4.1.7 on 2023-12-03 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0004_delete_blog_makessdsr'),
        ('shared_app', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='report_images/')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repoted', to='shared_app.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogger.blog_maker')),
            ],
        ),
    ]
